/* Generated By:JavaCC: Do not edit this line. KarloffConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface KarloffConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MAIN = 5;
  /** RegularExpression Id. */
  int ACHAVES = 6;
  /** RegularExpression Id. */
  int FCHAVES = 7;
  /** RegularExpression Id. */
  int VOID = 8;
  /** RegularExpression Id. */
  int NVAR = 9;
  /** RegularExpression Id. */
  int PV = 10;
  /** RegularExpression Id. */
  int INT = 11;
  /** RegularExpression Id. */
  int BOOL = 12;
  /** RegularExpression Id. */
  int IGUAL = 13;
  /** RegularExpression Id. */
  int APAR = 14;
  /** RegularExpression Id. */
  int FPAR = 15;
  /** RegularExpression Id. */
  int IF = 16;
  /** RegularExpression Id. */
  int THEN = 17;
  /** RegularExpression Id. */
  int WHILE = 18;
  /** RegularExpression Id. */
  int REPEAT = 19;
  /** RegularExpression Id. */
  int UNTIL = 20;
  /** RegularExpression Id. */
  int RETURN = 21;
  /** RegularExpression Id. */
  int SOUT = 22;
  /** RegularExpression Id. */
  int TRUE = 23;
  /** RegularExpression Id. */
  int FALSE = 24;
  /** RegularExpression Id. */
  int VIRGULA = 25;
  /** RegularExpression Id. */
  int FUNC = 26;
  /** RegularExpression Id. */
  int OP = 27;
  /** RegularExpression Id. */
  int ID = 28;
  /** RegularExpression Id. */
  int NUM = 29;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"main\"",
    "\"{\"",
    "\"}\"",
    "\"void\"",
    "\"newVar\"",
    "\";\"",
    "\"int\"",
    "\"bool\"",
    "\"=\"",
    "\"(\"",
    "\")\"",
    "\"if\"",
    "\"then\"",
    "\"while\"",
    "\"repeat\"",
    "\"until\"",
    "\"return\"",
    "\"System.output\"",
    "\"true\"",
    "\"false\"",
    "\",\"",
    "\"func\"",
    "<OP>",
    "<ID>",
    "<NUM>",
  };

}
